# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import form

class Ui_Widget(object):

    def openWindow(self, window):
        window.show()
        self.Widget.close()
        print('Nice!')

    def setupUi(self, Widget, window):
        Widget.setObjectName("Widget")
        Widget.resize(800, 600)
        self.Widget = Widget
        
        self.button = QtWidgets.QPushButton(Widget)
        self.button.setText('Open')
        self.button.setGeometry(QtCore.QRect(20, 20, 60, 60))
        self.button.clicked.connect(lambda : self.openWindow(window))


    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)

    Widget2 = QtWidgets.QWidget()
    ui2 = form.Ui_Widget()
    ui2.setupUi(Widget2)

    Widget = QtWidgets.QWidget()
    ui = Ui_Widget()
    ui.setupUi(Widget, Widget2)


    Widget.show()
    
    sys.exit(app.exec_())
