# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(900, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Widget.sizePolicy().hasHeightForWidth())
        Widget.setSizePolicy(sizePolicy)
        Widget.setStyleSheet("")
        self.scrollArea = QtWidgets.QScrollArea(Widget)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 671, 591))
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 652, 758))
        self.scrollAreaWidgetContents.setStyleSheet("")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(-1, -1, -1, 9)
        self.verticalLayout_2.setSpacing(1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textBrowser = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setStyleSheet("QTextBrowser {\n"
"  color: black;\n"
"  border: 1px solid black;\n"
"  border-radius: 0px;\n"
"  background-color: white\n"
"} ")
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout.addWidget(self.textBrowser)
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_2.sizePolicy().hasHeightForWidth())
        self.textBrowser_2.setSizePolicy(sizePolicy)
        self.textBrowser_2.setStyleSheet("QTextBrowser {\n"
"  color: black;\n"
"  border: 1px solid black;\n"
"  border-radius: 0px;\n"
"  background-color: white\n"
"} ")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.horizontalLayout.addWidget(self.textBrowser_2)
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_3.sizePolicy().hasHeightForWidth())
        self.textBrowser_3.setSizePolicy(sizePolicy)
        self.textBrowser_3.setStyleSheet("QTextBrowser {\n"
"  color: black;\n"
"  border: 1px solid black;\n"
"  border-radius: 0px;\n"
"  background-color: white\n"
"} ")
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.horizontalLayout.addWidget(self.textBrowser_3)
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_4.sizePolicy().hasHeightForWidth())
        self.textBrowser_4.setSizePolicy(sizePolicy)
        self.textBrowser_4.setStyleSheet("QTextBrowser {\n"
"  color: black;\n"
"  border: 1px solid black;\n"
"  border-radius: 0px;\n"
"  background-color: white\n"
"} ")
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.horizontalLayout.addWidget(self.textBrowser_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_5.sizePolicy().hasHeightForWidth())
        self.textBrowser_5.setSizePolicy(sizePolicy)
        self.textBrowser_5.setStyleSheet("QTextBrowser {\n"
"  color: black;\n"
"  border: 1px solid black;\n"
"  border-radius: 0px;\n"
"  background-color: rgba(0, 0, 0, 0)\n"
"} ")
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.horizontalLayout_2.addWidget(self.textBrowser_5)
        self.textBrowser_6 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_6.sizePolicy().hasHeightForWidth())
        self.textBrowser_6.setSizePolicy(sizePolicy)
        self.textBrowser_6.setStyleSheet("QTextBrowser {\n"
"  color: black;\n"
"  border: 1px solid black;\n"
"  border-radius: 0px;\n"
"  background-color: rgba(0, 0, 0, 0)\n"
"} ")
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.horizontalLayout_2.addWidget(self.textBrowser_6)
        self.textBrowser_7 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_7.sizePolicy().hasHeightForWidth())
        self.textBrowser_7.setSizePolicy(sizePolicy)
        self.textBrowser_7.setStyleSheet("QTextBrowser {\n"
"  color: black;\n"
"  border: 1px solid black;\n"
"  border-radius: 0px;\n"
"  background-color: rgba(0, 0, 0, 0)\n"
"} ")
        self.textBrowser_7.setObjectName("textBrowser_7")
        self.horizontalLayout_2.addWidget(self.textBrowser_7)
        self.textBrowser_8 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_8.sizePolicy().hasHeightForWidth())
        self.textBrowser_8.setSizePolicy(sizePolicy)
        self.textBrowser_8.setStyleSheet("QTextBrowser {\n"
"  color: black;\n"
"  border: 1px solid black;\n"
"  border-radius: 0px;\n"
"  background-color: rgba(0, 0, 0, 0)\n"
"} ")
        self.textBrowser_8.setObjectName("textBrowser_8")
        self.horizontalLayout_2.addWidget(self.textBrowser_8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.textBrowser_9 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_9.sizePolicy().hasHeightForWidth())
        self.textBrowser_9.setSizePolicy(sizePolicy)
        self.textBrowser_9.setStyleSheet("QTextBrowser {\n"
"  color: black;\n"
"  border: 1px solid black;\n"
"  border-radius: 0px;\n"
"  background-color: rgba(0, 0, 0, 0)\n"
"} ")
        self.textBrowser_9.setObjectName("textBrowser_9")
        self.horizontalLayout_5.addWidget(self.textBrowser_9)
        self.textBrowser_10 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_10.sizePolicy().hasHeightForWidth())
        self.textBrowser_10.setSizePolicy(sizePolicy)
        self.textBrowser_10.setStyleSheet("QTextBrowser {\n"
"  color: black;\n"
"  border: 1px solid black;\n"
"  border-radius: 0px;\n"
"  background-color: rgba(0, 0, 0, 0)\n"
"} ")
        self.textBrowser_10.setObjectName("textBrowser_10")
        self.horizontalLayout_5.addWidget(self.textBrowser_10)
        self.textBrowser_11 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_11.sizePolicy().hasHeightForWidth())
        self.textBrowser_11.setSizePolicy(sizePolicy)
        self.textBrowser_11.setStyleSheet("QTextBrowser {\n"
"  color: black;\n"
"  border: 1px solid black;\n"
"  border-radius: 0px;\n"
"  background-color: rgba(0, 0, 0, 0)\n"
"} ")
        self.textBrowser_11.setObjectName("textBrowser_11")
        self.horizontalLayout_5.addWidget(self.textBrowser_11)
        self.textBrowser_12 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_12.sizePolicy().hasHeightForWidth())
        self.textBrowser_12.setSizePolicy(sizePolicy)
        self.textBrowser_12.setStyleSheet("QTextBrowser {\n"
"  color: black;\n"
"  border: 1px solid black;\n"
"  border-radius: 0px;\n"
"  background-color: rgba(0, 0, 0, 0)\n"
"} ")
        self.textBrowser_12.setObjectName("textBrowser_12")
        self.horizontalLayout_5.addWidget(self.textBrowser_12)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.textBrowser_13 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_13.sizePolicy().hasHeightForWidth())
        self.textBrowser_13.setSizePolicy(sizePolicy)
        self.textBrowser_13.setStyleSheet("QTextBrowser {\n"
"  color: black;\n"
"  border: 1px solid black;\n"
"  border-radius: 0px;\n"
"  background-color: rgba(0, 0, 0, 0)\n"
"} ")
        self.textBrowser_13.setObjectName("textBrowser_13")
        self.horizontalLayout_6.addWidget(self.textBrowser_13)
        self.textBrowser_14 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_14.sizePolicy().hasHeightForWidth())
        self.textBrowser_14.setSizePolicy(sizePolicy)
        self.textBrowser_14.setStyleSheet("QTextBrowser {\n"
"  color: black;\n"
"  border: 1px solid black;\n"
"  border-radius: 0px;\n"
"  background-color: rgba(0, 0, 0, 0)\n"
"} ")
        self.textBrowser_14.setObjectName("textBrowser_14")
        self.horizontalLayout_6.addWidget(self.textBrowser_14)
        self.textBrowser_15 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_15.sizePolicy().hasHeightForWidth())
        self.textBrowser_15.setSizePolicy(sizePolicy)
        self.textBrowser_15.setStyleSheet("QTextBrowser {\n"
"  color: black;\n"
"  border: 1px solid black;\n"
"  border-radius: 0px;\n"
"  background-color: rgba(0, 0, 0, 0)\n"
"} ")
        self.textBrowser_15.setObjectName("textBrowser_15")
        self.horizontalLayout_6.addWidget(self.textBrowser_15)
        self.textBrowser_16 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_16.sizePolicy().hasHeightForWidth())
        self.textBrowser_16.setSizePolicy(sizePolicy)
        self.textBrowser_16.setStyleSheet("QTextBrowser {\n"
"  color: black;\n"
"  border: 1px solid black;\n"
"  border-radius: 0px;\n"
"  background-color: rgba(0, 0, 0, 0)\n"
"} ")
        self.textBrowser_16.setObjectName("textBrowser_16")
        self.horizontalLayout_6.addWidget(self.textBrowser_16)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.textBrowser_17 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_17.sizePolicy().hasHeightForWidth())
        self.textBrowser_17.setSizePolicy(sizePolicy)
        self.textBrowser_17.setStyleSheet("QTextBrowser {\n"
"  color: black;\n"
"  border: 1px solid black;\n"
"  border-radius: 0px;\n"
"  background-color: rgba(0, 0, 0, 0)\n"
"} ")
        self.textBrowser_17.setObjectName("textBrowser_17")
        self.horizontalLayout_7.addWidget(self.textBrowser_17)
        self.textBrowser_18 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_18.sizePolicy().hasHeightForWidth())
        self.textBrowser_18.setSizePolicy(sizePolicy)
        self.textBrowser_18.setStyleSheet("QTextBrowser {\n"
"  color: black;\n"
"  border: 1px solid black;\n"
"  border-radius: 0px;\n"
"  background-color: rgba(0, 0, 0, 0)\n"
"} ")
        self.textBrowser_18.setObjectName("textBrowser_18")
        self.horizontalLayout_7.addWidget(self.textBrowser_18)
        self.textBrowser_19 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_19.sizePolicy().hasHeightForWidth())
        self.textBrowser_19.setSizePolicy(sizePolicy)
        self.textBrowser_19.setStyleSheet("QTextBrowser {\n"
"  color: black;\n"
"  border: 1px solid black;\n"
"  border-radius: 0px;\n"
"  background-color: rgba(0, 0, 0, 0)\n"
"} ")
        self.textBrowser_19.setObjectName("textBrowser_19")
        self.horizontalLayout_7.addWidget(self.textBrowser_19)
        self.textBrowser_20 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_20.sizePolicy().hasHeightForWidth())
        self.textBrowser_20.setSizePolicy(sizePolicy)
        self.textBrowser_20.setStyleSheet("QTextBrowser {\n"
"  color: black;\n"
"  border: 1px solid black;\n"
"  border-radius: 0px;\n"
"  background-color: rgba(0, 0, 0, 0)\n"
"} ")
        self.textBrowser_20.setObjectName("textBrowser_20")
        self.horizontalLayout_7.addWidget(self.textBrowser_20)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.textBrowser_21 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_21.sizePolicy().hasHeightForWidth())
        self.textBrowser_21.setSizePolicy(sizePolicy)
        self.textBrowser_21.setStyleSheet("QTextBrowser {\n"
"  color: black;\n"
"  border: 1px solid black;\n"
"  border-radius: 0px;\n"
"  background-color: rgba(0, 0, 0, 0)\n"
"} ")
        self.textBrowser_21.setObjectName("textBrowser_21")
        self.horizontalLayout_8.addWidget(self.textBrowser_21)
        self.textBrowser_22 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_22.sizePolicy().hasHeightForWidth())
        self.textBrowser_22.setSizePolicy(sizePolicy)
        self.textBrowser_22.setStyleSheet("QTextBrowser {\n"
"  color: black;\n"
"  border: 1px solid black;\n"
"  border-radius: 0px;\n"
"  background-color: rgba(0, 0, 0, 0)\n"
"} ")
        self.textBrowser_22.setObjectName("textBrowser_22")
        self.horizontalLayout_8.addWidget(self.textBrowser_22)
        self.textBrowser_23 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_23.sizePolicy().hasHeightForWidth())
        self.textBrowser_23.setSizePolicy(sizePolicy)
        self.textBrowser_23.setStyleSheet("QTextBrowser {\n"
"  color: black;\n"
"  border: 1px solid black;\n"
"  border-radius: 0px;\n"
"  background-color: rgba(0, 0, 0, 0)\n"
"} ")
        self.textBrowser_23.setObjectName("textBrowser_23")
        self.horizontalLayout_8.addWidget(self.textBrowser_23)
        self.textBrowser_24 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_24.sizePolicy().hasHeightForWidth())
        self.textBrowser_24.setSizePolicy(sizePolicy)
        self.textBrowser_24.setStyleSheet("QTextBrowser {\n"
"  color: black;\n"
"  border: 1px solid black;\n"
"  border-radius: 0px;\n"
"  background-color: rgba(0, 0, 0, 0)\n"
"} ")
        self.textBrowser_24.setObjectName("textBrowser_24")
        self.horizontalLayout_8.addWidget(self.textBrowser_24)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.textBrowser_41 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_41.sizePolicy().hasHeightForWidth())
        self.textBrowser_41.setSizePolicy(sizePolicy)
        self.textBrowser_41.setStyleSheet("QTextBrowser {\n"
"  color: black;\n"
"  border: 1px solid black;\n"
"  border-radius: 0px;\n"
"  background-color: rgba(0, 0, 0, 0)\n"
"} ")
        self.textBrowser_41.setObjectName("textBrowser_41")
        self.horizontalLayout_13.addWidget(self.textBrowser_41)
        self.textBrowser_42 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_42.sizePolicy().hasHeightForWidth())
        self.textBrowser_42.setSizePolicy(sizePolicy)
        self.textBrowser_42.setStyleSheet("QTextBrowser {\n"
"  color: black;\n"
"  border: 1px solid black;\n"
"  border-radius: 0px;\n"
"  background-color: rgba(0, 0, 0, 0)\n"
"} ")
        self.textBrowser_42.setObjectName("textBrowser_42")
        self.horizontalLayout_13.addWidget(self.textBrowser_42)
        self.textBrowser_43 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_43.sizePolicy().hasHeightForWidth())
        self.textBrowser_43.setSizePolicy(sizePolicy)
        self.textBrowser_43.setStyleSheet("QTextBrowser {\n"
"  color: black;\n"
"  border: 1px solid black;\n"
"  border-radius: 0px;\n"
"  background-color: rgba(0, 0, 0, 0)\n"
"} ")
        self.textBrowser_43.setObjectName("textBrowser_43")
        self.horizontalLayout_13.addWidget(self.textBrowser_43)
        self.textBrowser_44 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_44.sizePolicy().hasHeightForWidth())
        self.textBrowser_44.setSizePolicy(sizePolicy)
        self.textBrowser_44.setStyleSheet("QTextBrowser {\n"
"  color: black;\n"
"  border: 1px solid black;\n"
"  border-radius: 0px;\n"
"  background-color: rgba(0, 0, 0, 0)\n"
"} ")
        self.textBrowser_44.setObjectName("textBrowser_44")
        self.horizontalLayout_13.addWidget(self.textBrowser_44)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.textBrowser_37 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_37.sizePolicy().hasHeightForWidth())
        self.textBrowser_37.setSizePolicy(sizePolicy)
        self.textBrowser_37.setStyleSheet("QTextBrowser {\n"
"  color: black;\n"
"  border: 1px solid black;\n"
"  border-radius: 0px;\n"
"  background-color: rgba(0, 0, 0, 0)\n"
"} ")
        self.textBrowser_37.setObjectName("textBrowser_37")
        self.horizontalLayout_12.addWidget(self.textBrowser_37)
        self.textBrowser_38 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_38.sizePolicy().hasHeightForWidth())
        self.textBrowser_38.setSizePolicy(sizePolicy)
        self.textBrowser_38.setStyleSheet("QTextBrowser {\n"
"  color: black;\n"
"  border: 1px solid black;\n"
"  border-radius: 0px;\n"
"  background-color: rgba(0, 0, 0, 0)\n"
"} ")
        self.textBrowser_38.setObjectName("textBrowser_38")
        self.horizontalLayout_12.addWidget(self.textBrowser_38)
        self.textBrowser_39 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_39.sizePolicy().hasHeightForWidth())
        self.textBrowser_39.setSizePolicy(sizePolicy)
        self.textBrowser_39.setStyleSheet("QTextBrowser {\n"
"  color: black;\n"
"  border: 1px solid black;\n"
"  border-radius: 0px;\n"
"  background-color: rgba(0, 0, 0, 0)\n"
"} ")
        self.textBrowser_39.setObjectName("textBrowser_39")
        self.horizontalLayout_12.addWidget(self.textBrowser_39)
        self.textBrowser_40 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_40.sizePolicy().hasHeightForWidth())
        self.textBrowser_40.setSizePolicy(sizePolicy)
        self.textBrowser_40.setStyleSheet("QTextBrowser {\n"
"  color: black;\n"
"  border: 1px solid black;\n"
"  border-radius: 0px;\n"
"  background-color: rgba(0, 0, 0, 0)\n"
"} ")
        self.textBrowser_40.setObjectName("textBrowser_40")
        self.horizontalLayout_12.addWidget(self.textBrowser_40)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.textBrowser_25 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_25.sizePolicy().hasHeightForWidth())
        self.textBrowser_25.setSizePolicy(sizePolicy)
        self.textBrowser_25.setStyleSheet("QTextBrowser {\n"
"  color: black;\n"
"  border: 1px solid black;\n"
"  border-radius: 0px;\n"
"  background-color: rgba(0, 0, 0, 0)\n"
"} ")
        self.textBrowser_25.setObjectName("textBrowser_25")
        self.horizontalLayout_9.addWidget(self.textBrowser_25)
        self.textBrowser_26 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_26.sizePolicy().hasHeightForWidth())
        self.textBrowser_26.setSizePolicy(sizePolicy)
        self.textBrowser_26.setStyleSheet("QTextBrowser {\n"
"  color: black;\n"
"  border: 1px solid black;\n"
"  border-radius: 0px;\n"
"  background-color: rgba(0, 0, 0, 0)\n"
"} ")
        self.textBrowser_26.setObjectName("textBrowser_26")
        self.horizontalLayout_9.addWidget(self.textBrowser_26)
        self.textBrowser_27 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_27.sizePolicy().hasHeightForWidth())
        self.textBrowser_27.setSizePolicy(sizePolicy)
        self.textBrowser_27.setStyleSheet("QTextBrowser {\n"
"  color: black;\n"
"  border: 1px solid black;\n"
"  border-radius: 0px;\n"
"  background-color: rgba(0, 0, 0, 0)\n"
"} ")
        self.textBrowser_27.setObjectName("textBrowser_27")
        self.horizontalLayout_9.addWidget(self.textBrowser_27)
        self.textBrowser_28 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_28.sizePolicy().hasHeightForWidth())
        self.textBrowser_28.setSizePolicy(sizePolicy)
        self.textBrowser_28.setStyleSheet("QTextBrowser {\n"
"  color: black;\n"
"  border: 1px solid black;\n"
"  border-radius: 0px;\n"
"  background-color: rgba(0, 0, 0, 0)\n"
"} ")
        self.textBrowser_28.setObjectName("textBrowser_28")
        self.horizontalLayout_9.addWidget(self.textBrowser_28)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.textBrowser_29 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_29.sizePolicy().hasHeightForWidth())
        self.textBrowser_29.setSizePolicy(sizePolicy)
        self.textBrowser_29.setStyleSheet("QTextBrowser {\n"
"  color: black;\n"
"  border: 1px solid black;\n"
"  border-radius: 0px;\n"
"  background-color: rgba(0, 0, 0, 0)\n"
"} ")
        self.textBrowser_29.setObjectName("textBrowser_29")
        self.horizontalLayout_10.addWidget(self.textBrowser_29)
        self.textBrowser_30 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_30.sizePolicy().hasHeightForWidth())
        self.textBrowser_30.setSizePolicy(sizePolicy)
        self.textBrowser_30.setStyleSheet("QTextBrowser {\n"
"  color: black;\n"
"  border: 1px solid black;\n"
"  border-radius: 0px;\n"
"  background-color: rgba(0, 0, 0, 0)\n"
"} ")
        self.textBrowser_30.setObjectName("textBrowser_30")
        self.horizontalLayout_10.addWidget(self.textBrowser_30)
        self.textBrowser_31 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_31.sizePolicy().hasHeightForWidth())
        self.textBrowser_31.setSizePolicy(sizePolicy)
        self.textBrowser_31.setStyleSheet("QTextBrowser {\n"
"  color: black;\n"
"  border: 1px solid black;\n"
"  border-radius: 0px;\n"
"  background-color: rgba(0, 0, 0, 0)\n"
"} ")
        self.textBrowser_31.setObjectName("textBrowser_31")
        self.horizontalLayout_10.addWidget(self.textBrowser_31)
        self.textBrowser_32 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_32.sizePolicy().hasHeightForWidth())
        self.textBrowser_32.setSizePolicy(sizePolicy)
        self.textBrowser_32.setStyleSheet("QTextBrowser {\n"
"  color: black;\n"
"  border: 1px solid black;\n"
"  border-radius: 0px;\n"
"  background-color: rgba(0, 0, 0, 0)\n"
"} ")
        self.textBrowser_32.setObjectName("textBrowser_32")
        self.horizontalLayout_10.addWidget(self.textBrowser_32)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.pushButton = QtWidgets.QPushButton(Widget)
        self.pushButton.setGeometry(QtCore.QRect(680, 130, 141, 31))
        self.pushButton.setStyleSheet("\n"
"QPushButton {\n"
"   \n"
"  display: inline-block;\n"
"  color: black;\n"
"  font-weight: 700;\n"
"  text-decoration: none;\n"
"  user-select: none;\n"
"  padding: .5em 2em;\n"
"  outline: none;\n"
"  border: 1px solid black;\n"
"  border-radius: 4px;\n"
"  transition: 0.2s;\n"
"background-color: white;\n"
"} \n"
"\n"
"QPushButton::hover{ background: rgb(235, 235, 235) }\n"
"QPushButton:pressed { background: rgb(221, 221, 221) }")
        self.pushButton.setObjectName("pushButton")
        self.comboBox = QtWidgets.QComboBox(Widget)
        self.comboBox.setGeometry(QtCore.QRect(680, 80, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("QComboBox {\n"
"    border: 1px solid black;\n"
"    border-radius: 4px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    background: white;\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"    background: white;\n"
"}\n"
"\n"
"/* QComboBox gets the \"on\" state when the popup is open */\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    background: grey;\n"
"}\n"
"\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"\n"
"    \n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    border: 2px solid white;\n"
"    selection-background-color: lightgray;\n"
"    background: white;\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label = QtWidgets.QLabel(Widget)
        self.label.setGeometry(QtCore.QRect(680, 50, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(Widget)
        self.pushButton_2.setGeometry(QtCore.QRect(820, 560, 71, 31))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.textBrowser.setHtml(_translate("Widget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">id</p></body></html>"))
        self.textBrowser_2.setHtml(_translate("Widget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">ФИО</p></body></html>"))
        self.textBrowser_3.setHtml(_translate("Widget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Опыт</p></body></html>"))
        self.textBrowser_4.setHtml(_translate("Widget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Класс</p></body></html>"))
        self.textBrowser_5.setHtml(_translate("Widget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1</p></body></html>"))
        self.textBrowser_6.setHtml(_translate("Widget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Нестеров Артемий Романович</p></body></html>"))
        self.textBrowser_7.setHtml(_translate("Widget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Нестеров Артемий Романович</p></body></html>"))
        self.textBrowser_8.setHtml(_translate("Widget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Нестеров Артемий Романович</p></body></html>"))
        self.textBrowser_9.setHtml(_translate("Widget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2</p></body></html>"))
        self.textBrowser_10.setHtml(_translate("Widget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Нестеров Артемий Романович</p></body></html>"))
        self.textBrowser_11.setHtml(_translate("Widget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Нестеров Артемий Романович</p></body></html>"))
        self.textBrowser_12.setHtml(_translate("Widget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Нестеров Артемий Романович</p></body></html>"))
        self.textBrowser_13.setHtml(_translate("Widget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">3</p></body></html>"))
        self.textBrowser_14.setHtml(_translate("Widget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Нестеров Артемий Романович</p></body></html>"))
        self.textBrowser_15.setHtml(_translate("Widget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Нестеров Артемий Романович</p></body></html>"))
        self.textBrowser_16.setHtml(_translate("Widget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Нестеров Артемий Романович</p></body></html>"))
        self.pushButton.setText(_translate("Widget", "PushButton"))
        self.comboBox.setItemText(0, _translate("Widget", "1 элемент"))
        self.comboBox.setItemText(1, _translate("Widget", "2 элемент"))
        self.label.setText(_translate("Widget", "Выбор маршрута"))
        self.pushButton_2.setText(_translate("Widget", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Widget = QtWidgets.QWidget()
    ui = Ui_Widget()
    ui.setupUi(Widget)
    Widget.show()
    sys.exit(app.exec_())
